site_name: Ivry CLI Documentation
theme:
  name: material
nav:
  - Introduction : index.md
  - Getting Started:
      - Windows Installation: getting-started/windows.md
      - Linux Installation: getting-started/linux.md
      - Mac Installation: getting-started/mac.md
  - CLI Reference: reference.md
  - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md