site_name: Ivry CLI Documentation
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate 
nav:
  - Introduction : index.md
  - Getting Started:
      - Windows Installation: getting-started/windows.md
      - Linux Installation: getting-started/linux.md
      - Mac Installation: getting-started/mac.md
  - Restart & Reconnect: 
      - Windows: restart/windows.md
      - Linux: restart/linux.md
      - Mac: restart/mac.md
  - CLI Reference: reference.md
  - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md
extra_css:
- stylesheets/extra.css
markdown_extensions:
  - pymdownx.superfences
  - def_list
  - attr_list
  - md_in_html